
hystrix:
  dashboard:
    proxy-stream-allow-list: "*"
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      default-zone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost
#spring:
#  cloud:
#    config:
#      enabled: true
#      uri: http://localhost:9296